### ISSUE TITLE
Option to exclude certain languages

### ISSUE THREAD

**Issue by Zeioth** [hinell/lsp-timeout.nvim#14] opened 2023-10-28 23:10 UTC
### Summary

New option `exclude = { 'markdown', ... }`.

So the plugin doesn't trigger for said language.

## Why
There are many scenarios where this is necessary. I'm gonna describe two.

## scenario 1
Imagine you are editing a markdown file.

You don't have a markdown lsp server, but you have prettierd as formatter.

When lsp-timeout run `:LspStop`, this is gonna also stop prettierd.

But it won't be possible to restore it with a LspAttach autocmd like next, because there is not lsp server at all.

```lua
      vim.api.nvim_create_autocmd({ "LspAttach" }, {
        desc = "Ensure null-ls start its sources a lsp client starts",
        callback = function()
           pcall(function() require("null-ls").enable({}) end)
        end,
      })
```

## scenario 2
Some LSP servers might just miss behave, and it would be a good idea to be able to ignore the language entirely.

* For example, java jdtls restores correctly, but it will send error notifications for a while.
![screenshot_2023-10-29_01-11-44_136919706](https://github.com/hinell/lsp-timeout.nvim/assets/3357792/35abf4ab-908f-47dc-89e8-feefb6cb794b)

**Comment by hinell** [comment] 2023-10-29 04:59
Duplicate of #10

**Closed** 2023-10-29 05:13 UTC
Labels: duplicate, enhancement
